version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      # route within the server:route within the container, it works like dropbox
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      # .env is generating on the server by the github workflow
      - ./.env

  backend:
    image: timurgain/foodgram_backend:latest
    restart: always
    volumes:
      - static_volume:/app/static_backend/
      - media_volume:/app/media_backend/
    ports:
     - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/result_build/:/app/result_build/
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/app/static_backend/
      - media_volume:/app/media_backend/
    depends_on:
      - backend
    
volumes:
  postgres_volume:
  static_volume:
  media_volume:


