# Generated by Django 2.2.19 on 2022-06-18 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0002_auto_20220616_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taginrecipe',
            old_name='recipies',
            new_name='recipie',
        ),
        migrations.RenameField(
            model_name='taginrecipe',
            old_name='tags',
            new_name='tag',
        ),
    ]
