# Generated by Django 2.2.19 on 2022-06-18 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodgram', '0003_auto_20220618_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taginrecipe',
            old_name='recipie',
            new_name='recipe',
        ),
    ]
