# Generated by Django 2.2.19 on 2022-06-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220611_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='Follow',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_following'),
        ),
    ]
